project 'ZHAutoSizeTagView-Example.xcodeproj'
platform :ios, '8.0'

target 'ZHAutoSizeTagView-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ZHAutoSizeTagView'

end
