project 'ZHAutoSizeTagView Example.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZHAutoSizeTagView Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  use_frameworks!
  # Pods for ZHAutoSizeTagView Example
  pod "ZHAutoSizeTagView", :path => "../ZHAutoSizeTagView.podspec"
end
